#!/usr/bin/env python3
"""Prove generated byte-buffer transfers own storage and unwind refusals."""
import argparse
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
p = argparse.ArgumentParser()
p.add_argument('--zen', type=Path, required=True)
args = p.parse_args()

with tempfile.TemporaryDirectory(prefix='zen-actor-buffers-') as folder:
    work = Path(folder)
    def generate(text):
        (work / 'main.zen').write_text(text)
        subprocess.run([str(args.zen.resolve()), 'build', str(work), '--emit-c', '-o', str(work / 'generated.c')],
                       env=dict(os.environ, ZEN_STD=str(ROOT / 'src')), check=True, timeout=120)
        return (work / 'generated.c').read_text()

    def check(name, source, expected=None, failure=False, timeout=20, timeout_failure=False, sanitizers='undefined'):
        (work / 'sender-finished').unlink(missing_ok=True)
        path = work / f'{name}.c'
        path.write_text(source)
        subprocess.run(['clang', '-O1', '-g', '-pthread', '-Wno-parentheses-equality',
                        '-fsanitize=' + sanitizers, '-fno-sanitize-recover=all', '-I', str(work), str(path), '-o', str(work / name)],
                       check=True, timeout=120)
        try:
            # A broken control must fail on every allocator: glibc and macOS
            # both fill freed memory when asked, so a use after free reads
            # garbage instead of the stale value a lazy allocator leaves.
            scribble = dict(os.environ, MALLOC_PERTURB_='165', MallocScribble='1') if failure else None
            result = subprocess.run([str(work / name)], cwd=work, capture_output=True, text=True, timeout=timeout, env=scribble)
        except subprocess.TimeoutExpired:
            assert timeout_failure, f'{name}: unexpected timeout'
            print(f'PASS: {name} detected deadlock')
            return
        if failure:
            assert result.returncode != 0, f'{name}: broken control unexpectedly passed'
        else:
            assert result.returncode == 0, f'{name}: {result.stdout}\n{result.stderr}'
            assert expected is None or result.stdout == expected, (name, result.stdout)
        print(f'PASS: {name}')

    source = generate((ROOT / 'tests/corpus/own/send_consumed_buffer.zen').read_text())
    retained_source = source
    check('retained-and-empty-buffer', source, 'retained 7 8\nempty grew 8\n')
    # The copy itself is essential, even if a fresh receiver allocator exists.
    broken, count = re.subn(r'memcpy\(bytes, msg->zg_arg\d+\.\w+, msg->zg_arg\d+\.\w+\);',
                            'memset(bytes, 99, 1);', source)
    assert count == 2, count
    check('corrupted-transfer-control', broken, failure=True)
    # Freeing transfer arenas after a turn invalidates values retained by state.
    # The freed bytes can still read back unchanged, so only ASan makes the
    # retained read fail reliably.
    marker = 'm->turn(a, m->data);'
    assert marker in source
    check('premature-release-control', source.replace(marker, marker + '\n zg_actor_release_owned(a->owned); a->owned = NULL;', 1),
          failure=True, sanitizers='address,undefined')

    paired = generate("""
Native = c.bind("stdlib.h", { abort* = () () })
Worker = {}
Worker.impl(Actor, {
    pair = (self :: @Self, ctx: Context, first: Vec<u8>, second: Vec<u8>) {
        a ::= first; b ::= second;
        a.add(3).match({ Ok(_) => (), Err(_) => Native.abort() });
        b.add(4).match({ Ok(_) => (), Err(_) => Native.abort() });
        a.get(0).match({ Ok(n) => println("first {} {}", n, a.len), None => Native.abort() });
        b.get(0).match({ Ok(n) => println("second {} {}", n, b.len), None => Native.abort() });
    }
})
main = (env: Env) Res<i32, AllocError | ActorStartError | ActorError> {
    arena ::= env.mem.alloc();
    a ::= arena.Vec<u8>(); b ::= arena.Vec<u8>();
    a.add(1).try(); b.add(2).try();
    worker = env.spawn(Worker()).try();
    worker.pair(consume a, consume b).try();
    worker.stop(); worker.join();
    Ok(0)
}
""")
    check('multiple-buffers-grow-independently', paired, 'first 1 2\nsecond 2 2\n')

    refusal = '''
Native = c.bind("stdlib.h", { abort* = () () })
Worker = {}
Worker.impl(Actor, {
    process = (self :: @Self, ctx: Context, data: Vec<u8>) { Native.abort(); }
})
main = (env: Env) Res<i32, AllocError | ActorStartError> {
    worker = env.spawn(Worker()).try();
    arena ::= env.mem.alloc();
    buf ::= arena.Vec<u8>();
    buf.add(7).try();
    worker.process(consume buf).match({
        Ok(_) => Native.abort(),
        Err(e) => e.match({ Full => println("refused"), _ => Native.abort() }),
    });
    worker.stop(); worker.join();
    Ok(0)
}
'''
    source = generate(refusal)
    found = re.search(r'static int (zg_actor_buffer\d+)\(zg_actor \*actor, void \*raw, zg_actor_owned \*\*pending\) \{', source)
    assert found, 'Missing generated transfer callback'
    symbol = found.group(1)
    source = source[:found.start(1)] + symbol + '_impl' + source[found.end(1):]
    source = source.replace('int main(', 'int zen_original_main(', 1)
    prefix = '''#include <stdlib.h>
#include <assert.h>
#include <pthread.h>
static pthread_mutex_t tracking = PTHREAD_MUTEX_INITIALIZER;
static _Thread_local int preparing;
static int call_index, denied, fail_at;
static void *live[16];
static size_t live_count;
static void *probe_malloc(size_t n) {
    if (preparing && call_index++ == fail_at) { denied++; return NULL; }
    void *p = malloc(n);
    if (preparing && p) { pthread_mutex_lock(&tracking); assert(live_count < 16); live[live_count++] = p; pthread_mutex_unlock(&tracking); }
    return p;
}
static void probe_free(void *p) {
    pthread_mutex_lock(&tracking);
    for (size_t i=0; i<live_count; i++) if (live[i] == p) { live[i] = live[--live_count]; break; }
    pthread_mutex_unlock(&tracking);
    free(p);
}
#define malloc probe_malloc
#define free probe_free
'''
    suffix = f'''
static int {symbol}(zg_actor *actor, void *raw, zg_actor_owned **pending) {{
    preparing = 1;
    int result = {symbol}_impl(actor, raw, pending);
    preparing = 0;
    return result;
}}
int main(int argc, char **argv) {{
    fail_at = FAIL_AT;
    int result = zen_original_main(argc, argv);
    assert(result == 0 && denied == 1 && live_count == 0);
    return result;
}}
'''
    accepted = retained_source.replace('int main(', 'int zen_original_main(', 1)
    symbols = re.findall(r'static int (zg_actor_buffer\d+)\(zg_actor \*actor, void \*raw, zg_actor_owned \*\*pending\) \{', accepted)
    wrappers = 'static void probe_noop(zg_actor *a, void *v) { (void)a; (void)v; }\n'
    for name in symbols:
        signature = f'static int {name}(zg_actor *actor, void *raw, zg_actor_owned **pending) {{'
        accepted = accepted.replace(signature, signature.replace(name, name + '_impl'), 1)
        wrappers += f'static int {name}(zg_actor *actor, void *raw, zg_actor_owned **pending) {{ assert(zg_actor_send(actor,probe_noop,NULL,SIZE_MAX,NULL,0)==2); preparing=1; int result={name}_impl(actor, raw, pending); preparing=0; return result; }}\n'
    wrappers += 'int main(int argc, char **argv) { fail_at=-1; int result=zen_original_main(argc,argv); assert(result==0 && call_index==5 && live_count==0); return result; }\n'
    check('shutdown-releases-all-transfer-storage', prefix + accepted + wrappers, 'retained 7 8\nempty grew 8\n')
    prepare_call = 'int ready = prepare(a, m->data, &owned);'
    assert prepare_call in accepted
    locked = accepted.replace(prepare_call, 'pthread_mutex_lock(&zg_actor_registry_lock); pthread_mutex_lock(&a->lock); ' + prepare_call + ' pthread_mutex_unlock(&a->lock); pthread_mutex_unlock(&zg_actor_registry_lock);', 1)
    check('callback-under-lock-control', prefix + locked + wrappers, failure=True, timeout=3, timeout_failure=True)
    release = 'zg_actor_release_owned(a->owned); a->owned = NULL;'
    assert release in accepted
    check('missing-shutdown-release-control', prefix + accepted.replace(release, '', 1) + wrappers, failure=True)
    for allocation in range(3):
        check(f'refusal-unwinds-allocation-{allocation}', prefix + source + suffix.replace('FAIL_AT', str(allocation)), 'refused\n')
    cleanup = 'if (!ready) { zg_actor_release_owned(owned); owned = NULL; }'
    assert cleanup in source
    check('missing-refusal-cleanup-control', prefix + source.replace(cleanup, 'if (!ready) { owned = NULL; }', 1) + suffix.replace('FAIL_AT', '2'), failure=True)
    stopped = generate(refusal.replace('Full => println("refused")', 'Closed => println("closed")'))
    signature = f'static int {symbol}(zg_actor *actor, void *raw, zg_actor_owned **pending) {{'
    assert signature in stopped
    stopped = stopped.replace(signature, signature.replace(symbol, symbol + '_impl'), 1)
    stopped = stopped.replace('int main(', 'int zen_original_main(', 1)
    stopped = stopped.replace('if (a->stopped) a->stopped(a);', 'assert(a->preparing == 0 && a->count == 0 && a->bytes == 0); if (a->stopped) a->stopped(a);', 1)
    watch = """
#include <sched.h>
static pthread_cond_t *watched_wake;
static int waited;
static int probe_wait(pthread_cond_t *condition, pthread_mutex_t *lock) {
    if (condition == watched_wake) __atomic_add_fetch(&waited,1,__ATOMIC_RELAXED);
    return pthread_cond_wait(condition,lock);
}
#define pthread_cond_wait probe_wait
"""
    pause = """
    zg_actor_stop(actor);
    pthread_mutex_lock(&actor->lock);
    watched_wake = &actor->wake;
    pthread_cond_signal(&actor->wake);
    pthread_mutex_unlock(&actor->lock);
    while (!__atomic_load_n(&waited,__ATOMIC_RELAXED)) sched_yield();
"""
    stop_suffix = suffix.replace('preparing = 0;', 'preparing = 0;' + pause).replace('FAIL_AT', '-1').replace('denied == 1', 'denied == 0 && call_index == 3')
    check('stop-waits-for-preparation-and-unwinds', prefix + watch + stopped + stop_suffix, 'closed\n')
    waiting = 'while (!a->head && (a->open || a->preparing))'
    assert waiting in stopped
    check('early-stopped-control', prefix + watch + stopped.replace(waiting, 'while (!a->head && a->open)', 1) + stop_suffix, failure=True)
    closed = generate(refusal.replace('    worker.process(consume buf)', '    worker.stop(); worker.join();\n    worker.process(consume buf)').replace('Full => println("refused")', 'Closed => println("closed")'))
    # No preparation callback is allowed to run for a closed mailbox.
    found = re.search(r'static int (zg_actor_buffer\d+)\(zg_actor \*actor, void \*raw, zg_actor_owned \*\*pending\) \{', closed)
    assert found and found.group(1) == symbol
    closed = closed[:found.start(1)] + symbol + '_impl' + closed[found.end(1):]
    closed = closed.replace('int main(', 'int zen_original_main(', 1)
    check('closed-does-not-allocate', prefix + closed + suffix.replace('FAIL_AT', '0').replace('denied == 1', 'denied == 0 && call_index == 0'), 'closed\n')
    concurrent_fixture = ROOT / 'tests/library/actor-buffers'
    (work / 'probe.h').write_text((concurrent_fixture / 'probe.h').read_text())
    concurrent = generate((concurrent_fixture / 'main.zen').read_text())
    prepared = re.search(r'static int (zg_actor_buffer\d+)\(zg_actor \*actor, void \*raw, zg_actor_owned \*\*pending\) \{', concurrent)
    message = re.search(r'typedef struct (zg_actor_message\d+) \{', concurrent)
    turn = re.search(r'static void (zg_actor_turn\d+)\(zg_actor \*zg_base, void \*zg_raw\) \{', concurrent)
    assert prepared and message and turn, 'Missing generated typed transfer ABI'
    name = prepared.group(1)
    concurrent = concurrent[:prepared.start(1)] + name + '_impl' + concurrent[prepared.end(1):]
    native = (concurrent_fixture / 'probe.c').read_text()
    for key, value in {'PREPARE': name, 'MESSAGE': message.group(1), 'TURN': turn.group(1)}.items():
        native = re.sub(r'\b' + key + r'(?=\b|_impl)', value, native)
    concurrent = concurrent.replace('int main(', 'int zen_original_main(', 1)
    tracker = prefix.replace('live[16]', 'live[4096]').replace('live_count < 16', 'live_count < 4096')
    tracker = tracker.replace('call_index++ == fail_at', '__atomic_fetch_add(&call_index,1,__ATOMIC_RELAXED) == fail_at')
    after = 'int main(int argc, char **argv) { fail_at=-1; int result=zen_original_main(argc,argv); assert(result==0 && call_index>2 && live_count==0); return result; }\n'
    check('concurrent-buffer-reservations', tracker + concurrent + native + after, 'PASS: concurrent buffer reservations drained 512 messages\n')
    print('PASS: buffer ownership, retained lifetime and all three allocation refusals')
