warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’ [-Wsign-compare]
warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int_t’ {aka ‘long int’} [-Wsign-compare]
warning: missing braces around initializer [-Wmissing-braces]
warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
warning: unused parameter ‘zu_larena’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbackend’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lbe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lctx’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_lc’ [-Wunused-parameter]
warning: unused parameter ‘zu_ldeclared’ [-Wunused-parameter]
warning: unused parameter ‘zu_ldoor’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lenv’ [-Wunused-parameter]
warning: unused parameter ‘zu_lexe’ [-Wunused-parameter]
warning: unused parameter ‘zu_lhasher’ [-Wunused-parameter]
warning: unused parameter ‘zu_lhasher’ [-Wunused-parameter]
warning: unused parameter ‘zu_lhasher’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_lid’ [-Wunused-parameter]
warning: unused parameter ‘zu_llo’ [-Wunused-parameter]
warning: unused parameter ‘zu_lmt’ [-Wunused-parameter]
warning: unused parameter ‘zu_lm’ [-Wunused-parameter]
warning: unused parameter ‘zu_lnode’ [-Wunused-parameter]
warning: unused parameter ‘zu_lnode’ [-Wunused-parameter]
warning: unused parameter ‘zu_lnode’ [-Wunused-parameter]
warning: unused parameter ‘zu_lnode’ [-Wunused-parameter]
warning: unused parameter ‘zu_lnode’ [-Wunused-parameter]
warning: unused parameter ‘zu_ln’ [-Wunused-parameter]
warning: unused parameter ‘zu_ln’ [-Wunused-parameter]
warning: unused parameter ‘zu_lprogram’ [-Wunused-parameter]
warning: unused parameter ‘zu_lp’ [-Wunused-parameter]
warning: unused parameter ‘zu_lp’ [-Wunused-parameter]
warning: unused parameter ‘zu_lrange’ [-Wunused-parameter]
warning: unused parameter ‘zu_lret’ [-Wunused-parameter]
warning: unused parameter ‘zu_lret’ [-Wunused-parameter]
warning: unused parameter ‘zu_lret’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lself’ [-Wunused-parameter]
warning: unused parameter ‘zu_lspan’ [-Wunused-parameter]
warning: unused parameter ‘zu_lspan’ [-Wunused-parameter]
warning: unused parameter ‘zu_lspan’ [-Wunused-parameter]
warning: unused parameter ‘zu_lstream’ [-Wunused-parameter]
warning: unused parameter ‘zu_ltparams’ [-Wunused-parameter]
warning: unused parameter ‘zu_ltree’ [-Wunused-parameter]
warning: unused parameter ‘zu_lty’ [-Wunused-parameter]
warning: unused parameter ‘zu_lty’ [-Wunused-parameter]
warning: unused parameter ‘zu_lvariant’ [-Wunused-parameter]
warning: unused parameter ‘zu_lwant’ [-Wunused-parameter]
warning: unused parameter ‘zu_lx’ [-Wunused-parameter]
warning: unused variable ‘zu_lchoice’ [-Wunused-variable]
warning: unused variable ‘zu_le’ [-Wunused-variable]
warning: unused variable ‘zu_lm_’ [-Wunused-variable]
warning: unused variable ‘zu_lword_’ [-Wunused-variable]
warning: unused variable ‘zu_lword_’ [-Wunused-variable]
warning: unused variable ‘zu_lword_’ [-Wunused-variable]
warning: variable ‘zg_cli_spec’ set but not used [-Wunused-but-set-variable]
warning: variable ‘zg_cli_spec’ set but not used [-Wunused-but-set-variable]
warning: variable ‘zu_lalloc_ty’ set but not used [-Wunused-but-set-variable]
